; 作品名インデックス検索のカテゴリー表示設定
; [category_order] … 書いた順にカテゴリーを表示。未記載のカテゴリーは後ろに追加される
; [category_hidden] … 書いたカテゴリーを非表示にする(「その他」「全部」も指定可能)
[category_order]
category_name[]=アニメ
category_name[]=ゲーム
category_name[]=特撮
category_name[]=ボカロ

;[category_hidden]
;category_name[]=例レーベル
;category_name[]=その他
;category_name[]=全部
